SoftwareCountry/arcadian-assistant

mobile/src/people/avatar.tsx, mobile/src/profile/profile.tsx
- noInnerBorder prop added
- image border calculation refined according to the design
=> noInnerBorder prop added

mobile/src/reducers/user/user.epics.ts
loadUserEmployeeFinished - sent only once to avoid endless employees load.
=> loadUserEmployeeFinished - sent only once

mobile/src/reducers/organization/organization.epics.ts, mobile/src/reducers/organization/organization.reducer.ts
- debounceTime removed after performance tests
- loadEmployeesForRoomEpic was missing in epics combine and never used
=> Minor performance&functionality fix

mobile/src/calendar/calendar-page-weekday.tsx
Use native events instead of TouchableOpacity, which uses PanResponder under the hood.
=> Improve swipe.

mobile/src/calendar/calendar-page.tsx, mobile/src/calendar/styles.ts
Fix overlapping when opacity < 1
#154
=> Fix issue #154.

mobile/src/employee-details/employee-details-events-list.tsx, mobile/src/employee-details/employee-details.tsx, mobile/src/reducers/calendar/calendar-events.reducer.ts
show opacity < 1 when event is outdated
=> Show all events on Profile.

server/Arcadia.Assistant.Web/Startup.cs, server/Arcadia.Assistant.Web/Users/UserEmployeeSearch.cs
=> UserEmployeeSearch

mobile/src/employee-details/employee-details-events-list.tsx
=> Fix: Сompleted Sick leave doesn't have title in Event section

mobile/src/navigation/search-view-styles.tsx, mobile/src/navigation/search-view.tsx
Use display style instead of variable to hide the text input
=> Fix seach text input

mobile/src/feeds/home-feeds-screen.tsx, mobile/src/reducers/organization/employees.reducer.spec.ts, mobile/src/reducers/organization/employees.reducer.ts, mobile/src/reducers/organization/organization.action.ts, mobile/src/reducers/organization/organization.epics.ts, mobile/src/reducers/people/people.reducer.ts
1. Passing loaded employees as an array instead of passing one by one;
2. Home Feeds -> shouldComponentUpdate removed;
3. equality check is added to Employees Reducer.
=> Company Structure screen performance optimizations

mobile/src/feeds/home-feeds-screen.tsx, mobile/src/feeds/styles.ts, mobile/src/navigation/loading.tsx
1. onEndReachedThreshold has to be >0 to onEndReached to be fired on Android
2. Footer with activity indicator is added
=> On Android feeds do not load next page when list is scrolled to the bottom #249

mobile/src/navigation/search-view-styles.tsx, mobile/src/navigation/search-view.tsx
=> #252: Better search bar

mobile/src/app.tsx, mobile/src/navigation/routes.ts, mobile/src/profile/profile-screen.tsx
1. Going back on the profile tab will not bring you to the feeds tab anymore;
2. Android back button handling is fixed.
=> #191: Navigation logic fixed

server/Arcadia.Assistant.Calendar/Arcadia.Assistant.Calendar.csproj, server/Arcadia.Assistant.Calendar/SickLeave/EmployeeSickLeaveActor.cs, server/Arcadia.Assistant.Calendar/SickLeave/SendEmailSickLeaveActor.cs, server/Arcadia.Assistant.DI/OrganizationModule.cs, server/Arcadia.Assistant.Notifications.Abstractions/Arcadia.Assistant.Notifications.Abstractions.csproj, server/Arcadia.Assistant.Notifications.Abstractions/BaseNotificationsActor.cs, server/Arcadia.Assistant.Notifications.Abstractions/NotificationEventBusMessage.cs, server/Arcadia.Assistant.Organization.Abstractions/EmployeeMetadataUpdatedEventBusMessage.cs, server/Arcadia.Assistant.Organization/EmployeeActor.cs, server/Arcadia.Assistant.Server/ActorSystemBuilder.cs, server/Arcadia.Assistant.sln
=> Use event stream for sick leave email notifications

server/Arcadia.Assistant.Calendar/Vacations/EmployeeVacationsActor.cs, server/Arcadia.Assistant.DI/NotificationsModule.cs, server/Arcadia.Assistant.DI/OrganizationModule.cs, server/Arcadia.Assistant.Organization/EmployeeActor.cs, server/Arcadia.Assistant.Organization/EmployeesActor.cs, server/Arcadia.Assistant.Organization/OrganizationActor.cs, server/Arcadia.Assistant.Server/DependencyInjection.cs
=> Removed timeout usings from every actor except health actor.

server/Arcadia.Assistant.Calendar.Abstractions/CalendarEventStatuses.cs, server/Arcadia.Assistant.Security/EmployeePermissionsEntry.cs, server/Arcadia.Assistant.Security/PermissionsActor.cs, server/Arcadia.Assistant.Web/Authorization/Handlers/EditCalendarEventsPermissionHandler.cs
=> Support new permission cancel approved vacations

mobile/src/calendar/calendar-page-weekday.tsx, mobile/src/calendar/calendar-page.tsx, mobile/src/calendar/calendar-pager.tsx, mobile/src/layout/style.tsx
TapGestureHandler and PanGestureHandler are used. maxDist={50} is set for TapGestureHandler,  minDist={20} is set for PanGestureHandler.
=> Day selection on the Calendar screen is fixed on Android

mobile/src/calendar/event-dialog/dayoff-requested-dialog.tsx, mobile/src/calendar/event-dialog/event-dialog-base.tsx, mobile/src/calendar/event-dialog/event-dialog.tsx, mobile/src/calendar/event-dialog/vacation-requested-dialog.tsx, mobile/src/reducers/calendar/calendar.action.ts, mobile/src/reducers/calendar/calendar.epics.ts, mobile/src/reducers/calendar/dayoff.epics.ts, mobile/src/reducers/calendar/event-dialog/event-dialog-type.model.ts, mobile/src/reducers/calendar/vacation.epics.ts
=> #301: Vacation/Dayoff requests confirmation

server/Arcadia.Assistant.Calendar/CalendarEventsStorageBase.cs
=> Calendar event isn't removed from pending actions

server/Arcadia.Assistant.Notifications.Push/Arcadia.Assistant.Notifications.Push.csproj, server/Arcadia.Assistant.Notifications.Push/Events/EmployeeDeviceRegistered.cs, server/Arcadia.Assistant.Notifications.Push/Events/EmployeeDeviceRemoved.cs, server/Arcadia.Assistant.Notifications.Push/GetDeviceIds.cs, server/Arcadia.Assistant.Notifications.Push/PushNotificationsDevicesActor.cs, server/Arcadia.Assistant.Notifications.Push/RegisterPushNotificationsDevice.cs, server/Arcadia.Assistant.Notifications.Push/RemovePushNotificationsDevice.cs, server/Arcadia.Assistant.Server.Interop/WellKnownActorPaths.cs, server/Arcadia.Assistant.Server/ActorSystemBuilder.cs, server/Arcadia.Assistant.Server/Arcadia.Assistant.Server.csproj, server/Arcadia.Assistant.Server/ServerActorsCollection.cs, server/Arcadia.Assistant.Web/Arcadia.Assistant.Web.csproj, server/Arcadia.Assistant.Web/Controllers/PushNotificationsController.cs, server/Arcadia.Assistant.Web/PushNotifications/IPushNotificationsService.cs, server/Arcadia.Assistant.Web/PushNotifications/PushNotificationsService.cs, server/Arcadia.Assistant.Web/Startup.cs, server/Arcadia.Assistant.sln
=> Push notifications support

mobile/src/employee-details/employee-details-screen.tsx, mobile/src/employee-details/employee-details.tsx, mobile/src/employee-details/styles.ts, mobile/src/profile/home-profile-screen.tsx, mobile/src/profile/styles.ts, mobile/src/reducers/organization/department.model.ts, mobile/src/reducers/organization/employee.model.ts
Employee details screen is refactored to have a full screen scroll and a refresh control
=> Employee details screen refactoring

server/Arcadia.Assistant.Configuration/Configuration/IPushSettings.cs, server/Arcadia.Assistant.Configuration/Configuration/MessagingSettings.cs, server/Arcadia.Assistant.Configuration/Configuration/PushSettings.cs, server/Arcadia.Assistant.DI/Arcadia.Assistant.DI.csproj, server/Arcadia.Assistant.DI/ConfigurationModule.cs, server/Arcadia.Assistant.DI/NotificationsModule.cs, server/Arcadia.Assistant.Notifications.Email/EmailNotificationsActor.cs, server/Arcadia.Assistant.Notifications.Push/Arcadia.Assistant.Notifications.Push.csproj, server/Arcadia.Assistant.Notifications.Push/GetDevicePushTokens.cs, server/Arcadia.Assistant.Notifications.Push/PushNotification.cs, server/Arcadia.Assistant.Notifications.Push/PushNotificationContent.cs, server/Arcadia.Assistant.Notifications.Push/PushNotificationTarget.cs, server/Arcadia.Assistant.Notifications.Push/PushNotificationsActor.cs, server/Arcadia.Assistant.Notifications.Push/PushNotificationsDevicesActor.cs, server/Arcadia.Assistant.Server.Console/Program.cs, server/Arcadia.Assistant.Server.Console/appsettings.json, server/Arcadia.Assistant.Server/ActorSystemBuilder.cs, server/Arcadia.Assistant.Server/Application.cs, server/Arcadia.Assistant.Server/Arcadia.Assistant.Server.csproj, server/Arcadia.Assistant.Server/DependencyInjection.cs, server/Arcadia.Assistant.Web/Controllers/PushNotificationsController.cs
=> Push notifications actor

server/Arcadia.Assistant.Organization.Abstractions/OrganizationRequests/EmployeesQuery.cs, server/Arcadia.Assistant.Organization/EmployeeSearch.cs, server/Arcadia.Assistant.Web/Controllers/EmployeesController.cs
=> Filter employees by name

server/Arcadia.Assistant.Calendar.Abstractions/DatesPeriod.cs, server/Arcadia.Assistant.Calendar/CalendarEventsStorageBase.cs, server/Arcadia.Assistant.Web/Controllers/CalendarEventsController.cs
=> Restrict several calendar events of one type with intersected dates

server/Arcadia.Assistant.Calendar/CalendarEventsStorageBase.cs
=> Excluded event itself from intersection check.

server/Arcadia.Assistant.Calendar.Notifications/EventAssignedToApproverEmailNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/EventAssignedToApproverPushNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/EventStatusChangedEmailNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/EventStatusChangedPushNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/EventUserGrantedApprovalEmailNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/EventUserGrantedApprovalPushNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/SickLeaveApprovedEmailNotificationActor.cs, server/Arcadia.Assistant.Server.Console/appsettings.json
=> Add events dates in email notifications

mobile/ios/ArcadiaAssistant.xcodeproj/project.pbxproj, mobile/src/app.tsx, mobile/src/auth/react-native-fingerprint-scanner.d.ts, mobile/src/auth/refresh-token-storage.ts, mobile/src/fingerprint-popup/fingerprint-popup.ios.tsx, mobile/src/splash-screen/splash-screen.tsx
In previous version of iOS implementation storage itself was fingerprint protected, thus explicit login in the App component did work fine for iOS but lead to wrong behaviour on Android.
=> iOS fingerprint behaviour is refactored to be the same as Android’s one

server/Arcadia.Assistant.UserPreferences/UserPreferences.cs, server/Arcadia.Assistant.UserPreferences/UserPreferencesActor.cs
=> User preferences strange bug

server/Arcadia.Assistant.Calendar/Vacations/EmployeeVacationsActor.cs
=> User cannot edit vacation dates

server/Arcadia.Assistant.CSP/ArcadiaHealthChecker.cs, server/Arcadia.Assistant.CSP/CspDepartmentsStorage.cs, server/Arcadia.Assistant.CSP/CspEmployeesInfoStorage.cs, server/Arcadia.Assistant.CSP/Vacations/ArcadiaVacationCreditRegistry.cs, server/Arcadia.Assistant.CSP/Vacations/CspEmployeeVacationsRegistry.cs, server/Arcadia.Assistant.CSP/Vacations/EmployeeVacationApprovedAccountingReminderActor.cs, server/Arcadia.Assistant.Calendar/CalendarEventsApprovalsActor.cs, server/Arcadia.Assistant.Calendar/CalendarEventsStorageBase.cs, server/Arcadia.Assistant.Calendar/EmployeeCalendarActor.cs, server/Arcadia.Assistant.Calendar/Vacations/EmployeeVacationsActor.cs, server/Arcadia.Assistant.Calendar/Vacations/PersistentEmployeeVacationsRegistry.cs, server/Arcadia.Assistant.Notifications.Push/PushNotificationsActor.cs, server/Arcadia.Assistant.Organization.Abstractions/CalendarEventsApprovalsChecker.cs, server/Arcadia.Assistant.Web/Health/HealthService.cs
Used ex.ToString instead of ex.Message to have more detailed error messages.
=> Improve error messages

server/Arcadia.Assistant.CSP/Vacations/CspEmployeeVacationsRegistry.cs, server/Arcadia.Assistant.CSP/Vacations/CspEmployeeVacationsRegistryPropsFactory.cs, server/Arcadia.Assistant.CSP/Vacations/DatabaseVacationsCache.cs, server/Arcadia.Assistant.CSP/Vacations/VacationsSyncExecutor.cs, server/Arcadia.Assistant.Calendar.Abstractions/EventBus/CalendarEventRemoved.cs, server/Arcadia.Assistant.Calendar/PendingActions/EmployeePendingActionsActor.cs
=> CSP sync manual db update

mobile/src/employee-details/employee-details-events-list.tsx, mobile/src/reducers/calendar/calendar-event.model.ts
Processed events has the same description text as approved ones
=> #482 Processed vacation does not have status

server/Arcadia.Assistant.CSP/Vacations/EmployeeVacationApprovedAccountingReminderActor.cs, server/Arcadia.Assistant.Calendar.Notifications/EventAssignedToApproverEmailNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/EventStatusChangedEmailNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/EventUserGrantedApprovalEmailNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/SickLeaveApprovedEmailNotificationActor.cs
=> All date formats are changed to be the same as in mobile application.

mobile/src/calendar/event-dialog/edit-sick-leave-event-dialog.tsx, mobile/src/calendar/event-dialog/event-dialog-base.tsx
Disable dialog buttons if sick leave is not selected
=> #509 Not possible to prolong sick leave if the active date is out of the range of sick leave dates

server/Arcadia.Assistant.CSP/Vacations/CspEmployeeVacationsRegistry.cs, server/Arcadia.Assistant.Calendar/CalendarEventsStorageBase.cs, server/Arcadia.Assistant.Calendar/PendingActions/EmployeePendingActionsActor.cs, server/Arcadia.Assistant.Calendar/Vacations/EmployeeVacationsActor.cs
=> CSP sync fixes

server/Arcadia.Assistant.CSP/Model/ArcadiaCSPContext.cs, server/Arcadia.Assistant.CSP/Model/Employee.cs, server/Arcadia.Assistant.CSP/Model/VacationApprovals.cs, server/Arcadia.Assistant.CSP/Model/VacationCancellations.cs, server/Arcadia.Assistant.CSP/Model/Vacations.cs, server/Arcadia.Assistant.CSP/Vacations/CalendarEventWithAdditionalData.cs, server/Arcadia.Assistant.CSP/Vacations/EmployeeVacationApprovedAccountingReminderActor.cs, server/Arcadia.Assistant.CSP/Vacations/VacationsSyncExecutor.cs, server/Arcadia.Assistant.Calendar.Abstractions/CalendarEvent.cs, server/Arcadia.Assistant.Calendar.Notifications/DictionaryExtensions.cs, server/Arcadia.Assistant.Calendar.Notifications/EventAssignedToApproverEmailNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/EventAssignedToApproverPushNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/EventStatusChangedEmailNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/EventStatusChangedPushNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/EventUserGrantedApprovalEmailNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/EventUserGrantedApprovalPushNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/SickLeaveApprovedEmailNotificationActor.cs, server/Arcadia.Assistant.Calendar.Notifications/TemplateExpressionParser.cs, server/Arcadia.Assistant.Server.Console/appsettings.json, server/Arcadia.Assistant.sln.DotSettings
=> Add vacation cancel reason

server/Arcadia.Assistant.CSP/Model/ArcadiaCSPContext.cs, server/Arcadia.Assistant.CSP/Model/Employee.cs, server/Arcadia.Assistant.CSP/Model/SickLeaves.cs, server/Arcadia.Assistant.CSP/Model/VacationReadies.cs, server/Arcadia.Assistant.CSP/Model/Vacations.cs, server/Arcadia.Assistant.CSP/Vacations/CalendarEventWithAdditionalData.cs, server/Arcadia.Assistant.CSP/Vacations/CspEmployeeVacationsRegistry.cs, server/Arcadia.Assistant.CSP/Vacations/CspVacationsRegistry.cs, server/Arcadia.Assistant.CSP/Vacations/EmployeeVacationAccountingReadyReminderActor.cs, server/Arcadia.Assistant.CSP/Vacations/VacationsSyncExecutor.cs, server/Arcadia.Assistant.Calendar.Abstractions/VacationStatuses.cs, server/Arcadia.Assistant.Calendar/Vacations/EmployeeVacationsActor.cs, server/Arcadia.Assistant.DI/ArcadiaCspModule.cs, server/Arcadia.Assistant.Server.Console/appsettings.json
=> Add new vacation status

server/Arcadia.Assistant.Calendar.Notifications/SickLeaveApprovedEmailNotificationActor.cs, server/Arcadia.Assistant.Server.Console/appsettings.json
=> Added employee name to subject line of accounting email about approved sick leave.

mobile/src/calendar/vacation-action-button.tsx, mobile/src/employee-details/employee-details-events-list.tsx, mobile/src/reducers/calendar/calendar-event.model.ts
=> Added new vacation status to mobile application.

mobile/src/people/company-departments-level-animated-node.tsx
https://github.com/SoftwareCountry/arcadian-assistant/issues/559
=> Chiefs are clickable on company screen

mobile/src/employee-details/event-management-toolset.tsx
=> #561 Requests approval dialog: change phrases

server/Arcadia.Assistant.CSP/CspDepartmentsStorage.cs, server/Arcadia.Assistant.CSP/Model/ArcadiaCSPContext.cs, server/Arcadia.Assistant.CSP/Model/Employee.cs, server/Arcadia.Assistant.CSP/Model/SickLeaveAccepts.cs, server/Arcadia.Assistant.CSP/Model/SickLeaveCancellations.cs, server/Arcadia.Assistant.CSP/Model/SickLeaveCompletes.cs, server/Arcadia.Assistant.CSP/Model/SickLeaveRejects.cs, server/Arcadia.Assistant.CSP/Model/SickLeaves.cs, server/Arcadia.Assistant.CSP/SickLeaves/CalendarEventWithAdditionalData.cs, server/Arcadia.Assistant.CSP/SickLeaves/CspEmployeeSickLeavesRegistry.cs, server/Arcadia.Assistant.CSP/SickLeaves/CspEmployeeSickLeavesRegistryPropsFactory.cs, server/Arcadia.Assistant.CSP/SickLeaves/CspSickLeavesRegistry.cs, server/Arcadia.Assistant.CSP/SickLeaves/DatabaseSickLeavesCache.cs, server/Arcadia.Assistant.CSP/SickLeaves/SickLeavesSyncExecutor.cs, server/Arcadia.Assistant.Calendar.Abstractions/CheckDatesAvailability.cs, server/Arcadia.Assistant.Calendar.Abstractions/EmployeeSickLeaves/ApproveSickLeave.cs, server/Arcadia.Assistant.Calendar.Abstractions/EmployeeSickLeaves/IEmployeeSickLeavesRegistryPropsFactory.cs, server/Arcadia.Assistant.Calendar.Abstractions/EmployeeSickLeaves/InsertSickLeave.cs, server/Arcadia.Assistant.Calendar.Abstractions/EmployeeSickLeaves/UpdateSickLeave.cs, server/Arcadia.Assistant.Calendar.Abstractions/SickLeaveStatuses.cs, server/Arcadia.Assistant.Calendar/SickLeave/EmployeeSickLeaveActor.cs, server/Arcadia.Assistant.Calendar/SickLeave/PersistentEmployeeSickLeavesRegistry.cs, server/Arcadia.Assistant.Calendar/SickLeave/PersistentEmployeeSickLeavesRegistryPropsFactory.cs, server/Arcadia.Assistant.DI/ArcadiaCspModule.cs, server/Arcadia.Assistant.DI/OrganizationModule.cs, server/Arcadia.Assistant.Organization/EmployeeActor.cs, server/Arcadia.Assistant.Organization/EmployeesActor.cs, server/Arcadia.Assistant.Organization/OrganizationActor.cs
=> Sick leaves CSP database

server/Arcadia.Assistant.CSP/SickLeaves/SickLeavesSyncExecutor.cs, server/Arcadia.Assistant.CSP/Vacations/VacationsSyncExecutor.cs, server/Arcadia.Assistant.Web/Authorization/Handlers/EditCalendarEventsPermissionHandler.cs
=> Multiple sick leave approvals

server/Arcadia.Assistant.CSP/Configuration/SickLeavesAccountingReminderConfiguration.cs, server/Arcadia.Assistant.CSP/Configuration/VacationsAccountingReminderConfiguration.cs, server/Arcadia.Assistant.CSP/CspDepartmentsStorage.cs, server/Arcadia.Assistant.CSP/SickLeaves/SickLeaveEndingReminderActor.cs, server/Arcadia.Assistant.CSP/Vacations/VacationAccountingReadyReminderActor.cs, server/Arcadia.Assistant.DI/ArcadiaCspModule.cs, server/Arcadia.Assistant.Server.Console/appsettings.json
=> Sick leave complete reminder

server/Arcadia.Assistant.CSP/CspDepartmentsStorage.cs, server/Arcadia.Assistant.CSP/CspEmployeeQuery.cs, server/Arcadia.Assistant.CSP/CspEmployeesInfoStorage.cs, server/Arcadia.Assistant.CSP/Vacations/EmployeesQueryExecutor.cs, server/Arcadia.Assistant.Web/Authorization/Handlers/UserIsEmployeeHandler.cs, server/Arcadia.Assistant.Web/Infrastructure/JwtEventsHandler.cs
With direct query to override some conditions.
=> Replaced using of database view

server/Arcadia.Assistant.CSP/CspEmployeesInfoStorage.cs, server/Arcadia.Assistant.Organization.Abstractions/EmployeeMetadata.cs, server/Arcadia.Assistant.Organization/EmployeeSearch.cs
One for modern identity (email field) and one for legacy identity (login field + domain).
=> When searching employee by identity used both checks

server/Arcadia.Assistant.UserPreferences/UserPreferences.cs
=> Email notifications enabled by default.

mobile/src/employee-details/employee-details-events-list.tsx
short day name ahead of date at event details
=> User profile: events list - add day of the week to date string

mobile/src/employee-details/employee-details-events-list.tsx
#691 Profile: add events status description
=> #691 Profile: add events status description

server/Arcadia.Assistant.CSP/CspCalendarEventsApprovalsChecker.cs, server/Arcadia.Assistant.CSP/CspDepartmentsStorage.cs, server/Arcadia.Assistant.CSP/Vacations/VacationsPendingActionsRefreshActor.cs, server/Arcadia.Assistant.Calendar/PendingActions/EmployeePendingActionsActor.cs, server/Arcadia.Assistant.Configuration/Configuration/AppSettings.cs, server/Arcadia.Assistant.DI/ArcadiaCspModule.cs, server/Arcadia.Assistant.Organization.Abstractions/CalendarEventsApprovalsChecker.cs, server/Arcadia.Assistant.Organization.Abstractions/OrganizationRequests/GetNextCalendarEventApprover.cs, server/Arcadia.Assistant.Server.Console/appsettings.json
=> Change vacation approvals process

server/Arcadia.Assistant.Web/Controllers/GetFileWebController.cs
=> Added action attribute to disable caching of iOS and Android builds.
